[package]
name = "shimmer"
version = "0.1.0"
edition = "2021"
authors = ["John Alberse"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

use_f64 = []

[dependencies]
rand = "0.8.5"
